source/python/rubbish/host/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^files(.*)$', views.file_paths, name='files'),
    url(r'^delete$', views.delete_files, name='delete_files'),
]

source/python/rubbish/trashes/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<pk>[0-9]+)$', views.get, name='get'),
    url(r'^create$', views.create, name='create'),
    url(r'^jobs$', views.jobs, name='jobs'),
    url(r'^jobs/(?P<pk>[0-9]+)/delete$', views.delete_job, name='jobs-delete'),
    url(r'^(?P<pk>[0-9]+)/restore$', views.restore, name='restore'),
    url(r'^(?P<pk>[0-9]+)/delete$', views.delete, name='delete'),
    url(r'^(?P<pk>[0-9]+)/clean', views.clean, name='clean'),
    url(r'^(?P<pk>[0-9]+)/edit$', views.edit, name='edit'),
]

source/python/rubbish/web/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from trashes import urls as trashes_urls
from host import urls as host_url
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^host/', include(host_url, namespace='host')),
    url(r'^trashes/', include(trashes_urls, namespace='trashes')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/python/rubbish/trashes/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import os
from django.db import models
from django.dispatch import receiver
from django.db.models import signals


class Trash(models.Model):
   RESTORE_POLICY_CHOICES = (
       (None, 'None'),
       ('name', 'By Name'),
       ('size', 'By Size'),
       ('last_modified', 'By Last Modified'),
   )

   AUTOCLEAN_POLICY_CHOICES = (
       (None, 'None'),
       ('size', 'By Size'),
       ('last_modified', 'By Last Modified'),
   )

   name = models.CharField(max_length=256, unique=True)
   location_path = models.CharField(max_length=256, unique=True, default="~/.trash")
   log_path = models.CharField(max_length=256, default='~/.trash.log')
   restore_policy = models.CharField(max_length=32, default=None, choices=RESTORE_POLICY_CHOICES, blank=True, null=True)
   autoclean_policy = models.CharField(max_length=32, default=None, choices=AUTOCLEAN_POLICY_CHOICES, blank=True, null=True)
   keep_alive_time = models.IntegerField(default=0)
   keep_alive_size = models.IntegerField(default=0)

   def __str__(self):
       return """id={},
                 name={},
                 location_path={},
                 log_path={},
                 free_space={},
                 restore_policy={},
                 autoclean_policy={},
                 keep_alive_time={},
                 keep_alive_size={}""".format(self.id,
                                              self.name,
                                              self.location_path,
                                              self.log_path,
                                              self.free_space,
                                              self.restore_policy,
                                              self.autoclean_policy,
                                              self.keep_alive_time,
                                              self.keep_alive_size)


class Job(models.Model):
   name = models.CharField(max_length=256)
   total_bytes = models.IntegerField(default=0)
   bytes_processed = models.IntegerField(default=0)
   trash = models.ForeignKey(Trash, related_name='jobs')
   done = models.BooleanField(default=False)
   result = models.FileField(null=True)


@receiver(signals.post_delete, sender=Job)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    if instance.result:
        os.remove(instance.result.path)

source/python/rubbish/trashes/forms.py
from django import forms
from trashes.models import Trash


class TrashForm(forms.ModelForm):

    class Meta:
        model = Trash
        fields = ['name', 'restore_policy', 'autoclean_policy', 'keep_alive_time', 'keep_alive_size']

    def _check_name(self, name):
        if Trash.objects.filter(name=name).exists():
            raise forms.ValidationError("This Name is already exists")

    def clean_name(self):
        name = self.cleaned_data['name']
        if self.instance:
            if self.instance.name != name:
                self._check_name(name)
        else:
            self._check_name(name)
        return name

    def clean_keep_alive_time(self):
        keep_alive_time = self.cleaned_data['keep_alive_time']
        if keep_alive_time < 0:
            raise forms.ValidationError("Value must be > 0")
        return keep_alive_time

    def clean_keep_alive_size(self):
        keep_alive_size = self.cleaned_data['keep_alive_size']
        if keep_alive_size < 0:
            raise forms.ValidationError("Value must be > 0")
        return keep_alive_size

    def clean_restore_policy(self):
        restore_policy = self.cleaned_data['restore_policy']
        if restore_policy == 'None':
            return None
        return restore_policy

    def clean_autoclean_policy(self):
        autoclean_policy = self.cleaned_data['autoclean_policy']
        if autoclean_policy == 'None':
            return None
        return autoclean_policy

source/python/rubbish/trashes/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os

from django.shortcuts import render, redirect
from django.db import transaction
from django.forms.models import model_to_dict
from trashes.models import Trash, Job
from trashes.forms import TrashForm
from services import TrashService
from django.http import HttpResponse


TRASH_TEMPLATE = 'trash.html'
TRASH_CREATE_TEMPLATE = 'create.html'
TRASH_EDIT_TEMPLATE = 'edit.html'
JOB_TEMPLATE = 'job.html'

service = TrashService()


def get_context_data():
    context = {'trashes': Trash.objects.all()}
    return context


def get(request, pk, *args, **kwargs):
    try:
        trash = Trash.objects.get(id=pk)
    except Trash.DoesNotExist as e:
        return HttpResponse(404)

    context = get_context_data()
    context.update({'files': service.get_files(pk),
                    'trash': trash})

    return render(request, TRASH_TEMPLATE, context)


def create(request, *args, **kwargs):
    if request.method == 'POST':
        form = TrashForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data

            data['location_path'] = os.path.join('/polygon', data['name'])
            data['log_path'] = os.path.join('/log', data['name'])

            trash = Trash.objects.create(**data)
            service.init_trash(trash.id)

            return redirect('host:files', '')
        context = {'errors': form.errors}
        return render(request, TRASH_CREATE_TEMPLATE, context)
    else:
        return render(request, TRASH_CREATE_TEMPLATE)


def restore(request, pk, *args, **kwargs):
    try:
        trash = Trash.objects.get(id=pk)
    except Trash.DoesNotExists as e:
        return HttpResponse(404)

    if request.method == 'POST':
        paths = request.POST.getlist('paths')
        if paths:
            service.restore_files(trash.id, paths)
        return redirect('/trashes/{}'.format(pk))
    else:
        return HttpResponse(404)


def delete(request, pk, *args, **kwargs):
    try:
        trash = Trash.objects.get(id=pk)
    except Trash.DoesNotExists as e:
        return HttpResponse(404)

    if request.method == 'POST':
        paths = request.POST.getlist('paths')
        if paths:
            service.delete_files(pk, paths)
        return redirect('/trashes/{}'.format(pk))
    else:
        return HttpResponse(404)


def clean(request, pk, *args, **kwargs):
    try:
        trash = Trash.objects.get(id=pk)
    except Trash.DoesNotExists as e:
        return HttpResponse(404)

    if request.method == 'POST':
        trash = Trash.objects.get(id=pk)
        trash.delete()
        service.clean_trash(pk)

        return redirect('/host/files')
    else:
        return HttpResponse(404)


def edit(request, pk, *args, **kwargs):
    try:
        trash = Trash.objects.get(id=pk)
    except Trash.DoesNotExist as e:
        return HttpResponse(404)

    if request.method == 'GET':
        context = {'trash': trash,
                   'selected_restore_policy': trash.get_restore_policy_display(),
                   'selected_autoclean_policy': trash.get_autoclean_policy_display()}
        return render(request, TRASH_EDIT_TEMPLATE, context)
    else:
        form = TrashForm(request.POST, instance=trash)
        if form.is_valid():
            trash = form.save()
            service.edit_trash(trash.id)
            return redirect('host:files', '')
        else:
            context = {'trash': trash,
                       'selected_restore_policy': trash.get_restore_policy_display(),
                       'selected_autoclean_policy': trash.get_autoclean_policy_display(),
                       'errors': form.errors}
            return render(request, TRASH_EDIT_TEMPLATE, context)


def jobs(request, *args, **kwargs):
    context = get_context_data()
    context['jobs'] = []
    for job in Job.objects.all():
        data = model_to_dict(job)
        if data['done']:
            data['progress_percent'] = 100
        else:
            if data['total_bytes'] != 0:
                data['progress_percent'] = int(data['bytes_processed'] / data['total_bytes'] * 100)
            else:
                data['progress_percent'] = 100
        context['jobs'].append(data)
    return render(request, JOB_TEMPLATE, context)

def delete_job(request, pk, *args, **kwargs):
    try:
        job = Job.objects.get(id=pk)
    except Job.DoesNotExist:
        return HttpResponse(404)

    if request.method == 'POST':
        job.delete()
        return redirect('/trashes/jobs')
    else:
        return HttpResponse(404)

source/python/rubbish/trashes/templates/create.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/font-awesome.min.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/styles-checkbox.css" %}">
    </head>
    <body>
        <form id="trash-create-form" action="{% url "trashes:create" %}" method="post">
            {% csrf_token %}
            <h2>Create trash</h2>
            <div class="form-group">
                <label for="trash-name">Name:</label>
                <input name="name" type="text" class="form-control" id="trash-name" aria-describedby="emailHelp">
                {% if 'name' in errors %}
                    {{ errors.name }}
                {% endif %}
            </div>
            <div class="form-group choose-create-div-container">
                <div class="choose-create-div-text">
                    <b class="choose-create-text">
                        Restore policy:
                    </b>
                </div>
                <div class="dropdown">
                  <button id="trash-restore-policy" name="restore_policy" value="None" class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">None
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                      <li><a href="#" class="choose-restore-policy" value="None">None</a></li>
                      <li><a href="#" class="choose-restore-policy" value="name">By Name</a></li>
                      <li><a href="#" class="choose-restore-policy" value="size">By Size</a></li>
                      <li><a href="#" class="choose-restore-policy" value="last_modified">By Last Modified</a></li>
                  </ul>
                  <input id="trash-restore-policy-input" type="hidden" name="restore_policy" value=None>
                </div>
            </div>
            <div class="form-group choose-create-div-container">
                <div class="choose-create-div-text">
                    <b class="choose-create-text">
                        Autoclean policy:
                    </b>
                </div>
                <div class="dropdown">
                  <button id="trash-autoclean-policy" name="autoclean_policy" value="None" class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">None
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                      <li><a href="#" class="choose-autoclean-policy" value="None">None</a></li>
                      <li><a href="#" class="choose-autoclean-policy" value="size">By Size</a></li>
                      <li><a href="#" class="choose-autoclean-policy" value="last_modified">By Last Modified</a></li>
                  </ul>
                  <input id="trash-autoclean-policy-input" type="hidden" name="autoclean_policy" value=None>
                </div>
            </div>
            <div class="form-group">
                <label for="trash-keep-alive-time">Live time:</label>
                <input name="keep_alive_time" type="text" class="form-control" id="trash-keep-alive-time">
                {% if 'keep_alive_time' in errors %}
                    {{ errors.keep_alive_time }}
                {% endif %}
                <small  class="form-text text-muted">0 - infinity time.</small>
            </div>
            <div class="form-group">
                <label for="trash-keep-alive-size">Live size:</label>
                <input name="keep_alive_size" type="text" class="form-control" id="trash-keep-alive-size">
                {% if 'keep_alive_size' in errors %}
                    {{ errors.keep_alive_size }}
                {% endif %}
                <small class="form-text text-muted">0 - infinity size.</small>
            </div>
            <button type="submit" class="btn btn-primary">Create</button>
            <button type="button" class="btn btn-default"><a href="{% url 'host:files' '' %}">Back</a></button>
        </form>
        <script src={% static "js/jquery-3.2.1.js" %}></script>
        <script src={% static "js/bootstrap.js" %}></script>
        <script src={% static "js/script.js" %}></script>
    </body>
</html>

source/python/rubbish/trashes/templates/edit.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/font-awesome.min.css" %}">
        <link rel="stylesheet" type="text/css" href="{% static "css/styles-checkbox.css" %}">
    </head>
    <body>
        <form id="trash-create-form" action="{% url "trashes:edit" trash.id %}" method="post">
            {% csrf_token %}
            <h2>Edit trash</h2>
            <div class="form-group">
                <label for="trash-name">Name:</label>
                <input name="name" type="text" class="form-control" id="trash-name" aria-describedby="emailHelp" value="{{ trash.name }}">
                {% if 'name' in errors %}
                    {{ errors.name }}
                {% endif %}
            </div>
            <div class="form-group choose-create-div-container">
                <div class="choose-create-div-text">
                    <b class="choose-create-text">
                        Restore policy:
                    </b>
                </div>
                <div class="dropdown">
                  <button id="trash-restore-policy" name="restore_policy" value="{{ trash.restore_policy }}" class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">{{ selected_restore_policy }}
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                      <li><a href="#" class="choose-restore-policy" value="None">None</a></li>
                      <li><a href="#" class="choose-restore-policy" value="name">By Name</a></li>
                      <li><a href="#" class="choose-restore-policy" value="size">By Size</a></li>
                      <li><a href="#" class="choose-restore-policy" value="last_modified">By Last Modified</a></li>
                  </ul>
                  <input id="trash-restore-policy-input" type="hidden" name="restore_policy" value=None>
                </div>
            </div>
            <div class="form-group choose-create-div-container">
                <div class="choose-create-div-text">
                    <b class="choose-create-text">
                        Autoclean policy:
                    </b>
                </div>
                <div class="dropdown">
                  <button id="trash-autoclean-policy" name="autoclean_policy" value="{{ trash.autoclean_policy }}" class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">{{ selected_autoclean_policy }}
                  <span class="caret"></span></button>
                  <ul class="dropdown-menu">
                      <li><a href="#" class="choose-autoclean-policy" value="None">None</a></li>
                      <li><a href="#" class="choose-autoclean-policy" value="size">By Size</a></li>
                      <li><a href="#" class="choose-autoclean-policy" value="last_modified">By Last Modified</a></li>
                  </ul>
                  <input id="trash-autoclean-policy-input" type="hidden" name="autoclean_policy" value=None>
                </div>
            </div>
            <div class="form-group">
                <label for="trash-keep-alive-time">Live time:</label>
                <input name="keep_alive_time" type="text" class="form-control" id="trash-keep-alive-time" value="{{ trash.keep_alive_time }}">
                {% if 'keep_alive_time' in errors %}
                    {{ errors.keep_alive_time }}
                {% endif %}
                <small  class="form-text text-muted">0 - infinity time.</small>
            </div>
            <div class="form-group">
                <label for="trash-keep-alive-size">Live size:</label>
                <input name="keep_alive_size" type="text" class="form-control" id="trash-keep-alive-size" value="{{ trash.keep_alive_size }}">
                {% if 'keep_alive_size' in errors %}
                    {{ errors.keep_alive_size }}
                {% endif %}
                <small class="form-text text-muted">0 - infinity size.</small>
            </div>
            <button type="submit" class="btn btn-primary">Edit</button>
            <button type="button" class="btn btn-default"><a href="{% url 'host:files' '' %}">Back</a></button>
        </form>
        <script src={% static "js/jquery-3.2.1.js" %}></script>
        <script src={% static "js/bootstrap.js" %}></script>
        <script src={% static "js/script.js" %}></script>
    </body>
</html>

source/python/rubbish/trashes/templates/job.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block source_block %}
    <div>
        <b class="trash-name">Jobs</b>
    </div>

    <table class="table trash-table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Action</th>
          <th>Progress</th>
          <th>Processed Bytes</th>
          <th>Total Bytes</th>
          <th>Result</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
      {% for job in jobs %}
        <tr>
            <td>#{{ job.id }}</td>
            <td>{{ job.name }}</td>
            <td>
                <div class="progress">
                  <div class="progress-bar" role="progressbar" aria-valuenow="{{ job.progress_percent }}%"
                  aria-valuemin="0" aria-valuemax="100" style="width:{{ job.progress_percent }}%">
                    {{ job.progress_percent }}%
                  </div>
                </div>
            </td>
            <td>{{ job.bytes_processed }}</td>
            <td>{{ job.total_bytes }}</td>
            <td>
                {% if job.result %}
                    <a href="{{ job.result.url }}" download="{{ job.result.name }}">
                        <button type="button" class="btn btn-default">
                            <img src="{% static "img/download.png" %}" class="log-download-img">
                        </button>
                    </a>
                {% else %}
                    <button type="button" class="btn btn-default disabled">
                        <img src="{% static "img/download.png" %}" class="log-download-img">
                    </button>
                {% endif %}
            </td>
            <td>
                <form action="{% url 'trashes:jobs-delete' job.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-default">
                        <img src="{% static "img/destroy.png" %}" class="log-delete-img">
                    </button>
                </form>
            </td>
        </tr>
      {% endfor %}
      </tbody>
    </table>
{% endblock source_block %}

source/python/rubbish/trashes/templates/trash.html
{% extends "base.html" %}
{% load static from staticfiles %}

{% block source_block %}
    <div>
        <b class="trash-name">{{ trash.name }}</b>
    </div>
    <!--<div>-->
        <!--<div class="progress trash-progress">-->
          <!--<div class="progress-bar" role="progressbar" aria-valuenow="{{ available_space_percent }}"-->
          <!--aria-valuemin="0" aria-valuemax="100" style="width:{{available_space_percent}}%">-->
            <!--{{available_space_percent}}%-->
          <!--</div>-->
        <!--</div>-->
        <!--<div class="container-fluid trash-info" style="display: flex;">-->
            <!--<div class="col-md-3">-->
                <!--<b>Used: {{ used }} GB</b>-->
            <!--</div>-->
            <!--<div class="col-md-9">-->
                <!--<b>Free: {{ free }} GB</b>-->
            <!--</div>-->
        <!--</div>-->
    <!--</div>-->
    <!--<div>-->
        <!--{% for part in partition_paths %}-->
            <!--<a class="trash-link" href="{% url 'host:paths' part.link %}">{{ part.name }}</a>-->
            <!--<span> / </span>-->
        <!--{% endfor %}-->
    <!--</div>-->
    <form class="trash-files-form" method="post">
        {% csrf_token %}
        <input type="hidden" id="trash-id" value="{{ trash.id }}">

        <div class="control-panel">
            <div class="checkbox select-all-trash-files-container">
                <input id="select-all-trash-files" type="checkbox" name="force">
                <label id="select-all-trash-files-label" for="select-all-trash-files">Select all</label>
            </div>
            <div class="trash-delete-button-div">
                <button type="submit" class="btn btn-default trash-delete-button">Delete selected</button>
            </div>
            <div class="trash-restore-button-div">
                <button type="submit" class="btn btn-default trash-restore-button">Restore selected</button>
            </div>
        </div>
        <table class="table trash-table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Origin Path</th>
              <th>Size</th>
              <th>Last Modified</th>
            </tr>
          </thead>
          <tbody>
          {% for file in files %}
            <tr>
                <td>
                    <div class="trash-name-column">
                        <div class="checkbox">
                            <input id={{ forloop.counter }} type="checkbox" class="trash-files-checkbox" name="paths" value="{{ file.trash_path }}">
                            <label for={{ forloop.counter }}></label>
                        </div>
                        <div>
                            {% if file.is_dir %}
                                <img src="{% static "img/folder.png" %}" class="trash-folder-img">
                                <span>{{ file.name }}</span>
                            {% else %}
                                <img src="{% static "img/file.png" %}" class="trash-file-img">
                                <span>{{ file.name }}</span>
                            {% endif %}
                        </div>
                    </div>
                </td>
                <td>{{ file.origin_path }}</td>
                <td>{{ file.size }}</td>
                <td>{{ file.timestamp }}</td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
        <div id="delete-trash-modal" class="modal fade">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Do you want to delete this files?</h4>
                    </div>
                    <div class="modal-body">
                        <div style="margin-bottom: 20px">
                            <p>Location:</p>
                            <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle trash-delete-modal-selected" type="button" data-toggle="dropdown">Choose one of this trash
                                <span class="caret"></span></button>
                                <ul class="dropdown-menu">
                                    {% for trash in trashes %}
                                        <li><a href="#" class="trash-delete-modal-select" value="{{ trash.id }}">{{ trash.name }}</a></li>
                                    {% endfor %}
                                </ul>
                                <input type="hidden" class="selected-trash-id" name="trash_id">
                            </div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        <button type="button" class="btn btn-primary delete-host-files disabled">Delete</button>
                    </div>
                </div>
            </div>
        </div>
    </form>

{% endblock source_block %}