source/python/rubbish/host/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^files(.*)$', views.file_paths, name='files'),
    url(r'^delete$', views.delete_files, name='delete_files'),
]

source/python/rubbish/trashes/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<pk>[0-9]+)$', views.get, name='get'),
    url(r'^create$', views.create, name='create'),
    url(r'^jobs$', views.jobs, name='jobs'),
    url(r'^jobs/(?P<pk>[0-9]+)/delete$', views.delete_job, name='jobs-delete'),
    url(r'^(?P<pk>[0-9]+)/restore$', views.restore, name='restore'),
    url(r'^(?P<pk>[0-9]+)/delete$', views.delete, name='delete'),
    url(r'^(?P<pk>[0-9]+)/clean', views.clean, name='clean'),
    url(r'^(?P<pk>[0-9]+)/edit$', views.edit, name='edit'),
]

source/python/rubbish/web/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from trashes import urls as trashes_urls
from host import urls as host_url
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^host/', include(host_url, namespace='host')),
    url(r'^trashes/', include(trashes_urls, namespace='trashes')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/python/rubbish/templates/base.html
<!DOCTYPE html>
{% load static from staticfiles %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/font-awesome.min.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/styles-checkbox.css" %}">
  </head>
  <body>
    <div class="container-fluid">
        <div class="menu col-sm-2 col-md-2" >
            <div class="menu-item">
                <img src="{% static "img/computer.png" %}" class="trash-computer-img">
                <a class="trash-link" href="{% url 'host:files' '' %}"><b class="menu-text">Host</b></a>
            </div>
            {% for trash in trashes %}
                <div class="menu-item">
                    <img src="{% static "img/trash.png" %}" class="trash-img">
                    <a class="trash-link" href="{% url 'trashes:get' trash.id %}"><b class="menu-text">{{ trash.name }}</b></a>
                    <div class="dropdown trash-action">
                        <img class="dropdown-toggle trash-img" data-toggle="dropdown" src="{% static "img/3dots.png" %}" class="trash-img">
                        <ul class="dropdown-menu" style="text-align: center;">
                            <a href="{% url 'trashes:edit' trash.id %}">
                                <button class="btn btn-default" type="submit">Edit</button>
                            </a>
                            <form action="{% url 'trashes:clean' trash.id %}" method="post" style="display: inline-table">
                                {% csrf_token %}
                                <button class="btn btn-default" type="submit">Delete</button>
                            </form>
                        </ul>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="col-sm-10 col-md-10 trash-source">
            {% block source_block %}
            {% endblock %}
        </div>
    </div>

    <div class="action-buttons">
        <div class="trash-job-img-container">
            <a href="{% url 'trashes:jobs'%}"><img src={% static "img/job.png" %} class='trash-job-img'></a>
        </div>
        <div>
            <a href="{% url 'trashes:create' %}">
                <img src={% static "img/plus.png" %} class='trash-plus-img'>
            </a>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src={% static "js/jquery-3.2.1.js" %}></script>
    <script src={% static "js/bootstrap.js" %}></script>
    <script src={% static "js/script.js" %}></script>
  </body>
</html>